kind: Pod
apiVersion: v1
metadata: 
  name: toleration
spec:

  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

  containers:
  - name: toleration
    image: nginx

