apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: chat-app

spec:
  selector:
    app: chat-app
    tier: database
  ports:
    - protocol: TCP
      port:  27017
      targetPort: 27017
  type: ClusterIP
  
---

kind: Secret
apiVersion: v1
metadata: 
  name: mongodb-secret
  namespace: chat-app
type: Opaque
data: 
  username: YWRtaW4=
  password: YWRtaW4xMjM=



---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mongodb
  namespace: chat-app 
  labels:
    app: chat-app
    tier: database

spec:
  replicas: 1
  serviceName: mongodb-service
  minReadySeconds: 10 
  selector: 
    matchLabels:
      app: chat-app
      tier: database
  
  template:
    metadata:
      labels:
        app: chat-app
        tier: database
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: storage
                operator: In
                values:
                - ssd
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: 
                secretKeyRef: 
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: mongodb-secret
                  key: password
       #  Node affinity is a set of rules used by the scheduler to determine where a pod can be placed in the cluster. It allows you to specify constraints on the nodes that a pod can be scheduled on based on labels, topology, or other node attributes. Node affinity can be used to ensure that pods are scheduled on specific types of nodes, such as those with certain hardware characteristics or geographic locations.
      tolerations:
        - key: "ssd"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
  volumeClaimTemplates:
    - metadata: 
        name: mongodb
      spec:
        accessModes: ["ReadWriteOnce"] 
        resources:
          requests:
            storage: 1Gi 
    
---

kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: mongodb-pdb
  namespace: chat-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: chat-app
      tier: database 

--- 

kind: PriorityClass
apiVersion: scheduling.k8s.io/v1
metadata:
  name: mongodb-priority
value: 1000
globalDefault: false
description: "Priority class for MongoDB pods"