kind: Pod
apiVersion: v1
metadata:
  name: hostpath-demo
  namespace: default

spec:
  volumes:
    - name: host-storage
      hostPath:
        path: /tmp-host-storage
        type: DirectoryOrCreate

  containers:
    - name: nginx
      image: nginx

      volumeMounts:
        - name: host-storage
          mountPath: /data

