kind: Deployment
apiVersion: apps/v1
metadata: 
  name: backend-deployment
  namespace: chat-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
      tier: backend

  template:
    metadata:
      name: backend-deployment
      labels:
        app: chat-app
        tier: backend
    
    spec:
      containers:
        - name: backend
          image: hardik002/chatapp-backend:latest
          ports:
          - containerPort: 5001
          env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "5001"
          - name: MONGODB_URI
            value: "mongodb://root:root@mongodb-service:27017/chatapp?authSource=admin"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: chat-app-secret
                key: JWT_SECRET 
    
    