kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-sc-pvc
  namespace: default

spec:
  storageClassName: my-storage
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
