kind: Pod
apiVersion: v1
metadata:
  name: demo-sc-pod

spec:
  containers:
    - name: nginx
      image: nginx

      volumeMounts:
        - name: storage
          mountPath: /data

  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: demo-sc-pvc
