kind: PersistentVolume
apiVersion: v1
metadata:
  name: demo-pv

spec:
  capacity:
    storage: 2Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain
    
  hostPath:
    path: /mnt/demo-storage
