apiVersion: v1
kind: Pod
metadata:
  name: secret-volume222222222222-demo

spec:
  containers:
  - name: demo
    image: busybox:1.36

    command:
    - sh
    - -c
    - |
      while true
      do
        echo "===== Username ====="
        cat /etc/secret/username

        echo
        echo "===== Password ====="
        cat /etc/secret/password

        echo
        echo "----------------------"
        sleep 10
      done

    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
      readOnly: true

  volumes:
  - name: secret-volume
    secret:
      secretName: mongo-secret
