kind: Pod
apiVersion: v1
metadata:
  name: secret-env-demo

spec:
  containers:
    - name: demo
      image: busybox:1.36

      command:
        - sh
        - -c
        - |
          while true
          do
            echo "Username: $DB_USERNAME"
            echo "Password: $DB_PASSWORD"
            echo "----------------"
            sleep 10
          done

      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
